import * as genresAPI from "./fakeGenreService";

const workPrograms = [
  {
    _id: 1,
    PostNr: 1,
    OrganisatieEenheid: "DBI",
    Afdeling: "Dienst Beheer Infrastructuur",
    Bureau: "Eenheid DBI",
    Kostenplaats: 464,
    DocumentNummer: 293117,
    LeverancierInkoopOmschrijving:
      "ENGIE ENERGIE NEDERLAND N.V.\n\nEnergiebelasting Cluster OVL juni 2018\n\nPZH_2018_637077952",
    BedragFactuur: "8948,13",
    BedragBesluit: "387000",
    SoortInkoop: "Levering",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "ja",
    KC3: "ja",
    KC4: "n.v.t.",
    KC5: "ja",
    KC6: "ja",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "n.v.t.",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "KC01: PHZ_nummer niet vermeld op factuur. Tarieven betreffen wettelijke tarieven en staan niet in een overeenkomst of opdrachtbrief.\nKC02a/b: Pommer van factuur is niet gelijk aan voorstel voor besluitvorming maar dit wordt veroorzaakt doordat de originele pommer een andere functie heeft gekregen en dus is vervangen; zie uitleg behandelend ambtenaar. Akkoord.\nKC02c/d: De pommer stelt vast dat de factuur gericht is aan zijn afdeling. Hij geeft aan dat hij aan de hand van dbenergie.nl vaststelt of de gefactureerde locatie een DBI_locatie is. Hij legt deze controle niet aantoonbaar vast. Hij voert geen controle uit op de tarieven (of verbruik). Hij houdt  wel een overzicht bij van de kosten per maand, per locatie waardoor een plausibiliteitscontrole mogelijk is. \nSM: Gesproken met Aat van Ek (Contractmanager) op 21_1_2019: hij geeft aan dat er een aanvullende controle wordt uitgevoerd door Trenton (een bedrijf dat gespecialiseerd is in controles van energiecontracten). Op dit moment stellen zij vast of de gefactureerde eancode op naam staat van PZH en of de juiste belastingcluster (tarief) wordt toegepast.Hierover wordt jaarlijks gerapporteerd; het rapport over 2018 is nog niet ontvangen. Aat van Ek heeft de energiecontracten sinds vorig jaar in beheer en is op dit moment bezig de controle op de contracten te verscherpen. Eerste punt die hierbij wordt opgepakt, is het in kaart brengen van de objecten en bijbehorende contracten, daarnaast gaat er een nieuwe aanbesteding plaatsvinden. Als dit is gedaan zal er worden gekeken of Trenton ook een trendanalyse kan uitvoeren op hrt verbruik. Dus ondanks dat de controle door de pommer niet op alle aspecten wordt uitgevoerd, wordt het risico door aanvullende werkzaamheden gemitigeerd. De tarieven op de factuur betreffen wettelijke tarieven milieubelastingen. AO/IC heeft als aanvullende zekerheid vastgesteld dat de tarieven op de factuur aansluiten met de Tabellen tarieven milieubelastingen op belastingdienst.nl. Tevens mede adhv van de ROVK 2017 (aantal MWH waarbij 1Mwh =1000kwh) vastgesteld dat de schijfindeling (50.001 t/m 10 mln kWh) logisch is. \nKC04: Geen inkoopplan aanwezig. Betreft de factuur voor de energiebelasting welke via Engie in rekening wordt gebracht, vastgesteld dat tarieven overeenkomen met belastingdienst.nl. De verplichting 2018 is via een AAA37 besluit vastgelegd, derhalve inkoopplan niet van toepassing.\nKC05: Raamcontract afgesloten met Engie.\nKC07 tm KC12: Betreft een uitvraag binnen de raamovereenkomst derhalve Besluit tot machtiging aanbesteding niet verplicht. \nKC13: Meerdere verplichtingen aangemaakt op 1 besluitnota, totaalbedrag verplichtingenadministratie is hoger dan bedrag op voorstel voor besluitvorming. Dit wordt veroorzaakt doordat de pommer gedurende het jaar is gewijzigd. Vastgesteld aan de hand van rapport verplichtingen 2014_2025 dat het totaal van de ontvangen facturen en lopende verplichting 2018 aansluit op het voorstel voor besluitvorming.\nKC14: Voorstel voor besluitvorming bevat verschillende kostenplaatsen. Nagevraagd bij crediteurenadministratie hoe zij weten op welke kostenplaats geboekt moet worden, crediteurenadministratie geeft aan dat de pommer moet aangeven op welke kostenplaats geboekt moet worden.",
    Controleur: "Shenita "
  },
  {
    _id: 2,
    PostNr: 2,
    OrganisatieEenheid: "DLB",
    Afdeling: "Samenleving & Economie",
    Bureau: "Cultuur en Vrije tijd",
    Kostenplaats: 395,
    DocumentNummer: 295487,
    LeverancierInkoopOmschrijving:
      "ART & FACTS\n\nUren Suzanne Hoeve Augustus 2018\n\nPZH_2018_654415048",
    BedragFactuur: " � 5.596,64 ",
    BedragBesluit: " � 15.000 ",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "ja",
    KC3: "ja",
    KC4: "nee",
    KC5: "ja",
    KC6: "ja",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "n.v.t.",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "KC02c: De factuur is geautoriseerd door de pommer nadat deze per mail (zie pag 19 post) goedkeuring heeft gevraagd aan de behandelend ambtenaar. De behandelend ambtenaar geeft dat zij heeft vastgesteld dat de ingehuurde medewerker op de uren in het depot is komen werken en op basis daarvan akkoord heeft gegeven voor de factuur. Zij heeft verder geen bewijs (bv urenbriefje) van de gewerkte uren. AO/IC heeft aanvullende bewijs gevraagd: De BA heeft email correspondentie (zie pag 21 post) gestuurd tussen de ingehuurde medewerker en PZH waaruit blijkt dat zij bezig is geweest met het opstellen van lijsten in Excel in het kader van haar gegeven opdracht. Hieruit blijkt in ieder geval dat zij werkzaam is geweest voor de provincie Zuid Holland.  Wel een opmerking in rapport.\nKC04: Enkelvoudige inkoopprocedure gevolgd. Originele opdracht incl. verlenging komt uit op �32k. Enkelvoudige procedure derhalve toegestaan. Geen inkoopplan opgesteld voor aanvullende opdracht.\nKC05: Vastgesteld dat totaal verplichtingen niet boven aanbestedingsgrens uitkomt.\nKC06: Tarief en de in rekening gebrachten reiskosten cf offerte. In opdrachtbevestiging en voorstel voor besluitvorming wordt gesproken over een raamovereenkomst, deze blijkt er niet te zijn.\nKC09 tm KC12: Geen advies gevraagd is ook niet meer verplicht sinds het vervallen van de verplichte consultatielijst. Zie controle op de inkoopbesluiten IC2 waar deze factuur in de controle zit.\nKC14: Akkoord. Boekingssleutel in CODA is gelijk aan die op de voorstel voor besluitvorming voor de verlenging. Echter boekingsleutel op voorstel voor besluitvorming van originele opdracht is anders; dit is nagevraagd bij JFA en die geeft aan dat boekingssleutel van de verlenging juist is (originele opdracht is onjuist), dit is op 11_1_2019 gecorrigeerd door FA. Correctie is van rekening 40424 naar 40404, derhalve risico beperkt.",
    Controleur: "Shenita"
  },
  {
    _id: 3,
    PostNr: 3,
    OrganisatieEenheid: "DRM",
    Afdeling: "Ruimte, Wonen en Bodem",
    Bureau: "Beleid",
    Kostenplaats: 437,
    DocumentNummer: 296123,
    LeverancierInkoopOmschrijving:
      "HASKONINGDHV NEDERLAND B.V.\n\nOpstellen en voorbereiden van een Leefomgevingstoets (planMER) voor het Omgevingsbeleid 2018: uren augustus\n\nPZH_2018_655787420",
    BedragFactuur: "16962,50 ",
    BedragBesluit: "50000 ",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "ja",
    KC3: "ja",
    KC4: "ja",
    KC5: "ja",
    KC6: "ja",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "n.v.t.",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "KC02c: Betreft het maken en voorbereiden van een leefomgevingstoets (planMER). De factuur is opgesteld zoals de offerte aangeeft namelijk: bestede tijd door de medewerkers van het bureau x uurtatief. De pommer (projectleider) geeft aan dat er geen directe controle plaatsvindt of de gefactureerde uren overeenkomen met de bestede uren maar dat de prestatie wordt beoordeeld op basis van tussenrapportages en eindrapportage (deze zijn ook als zodanig in de offerte vermeld). AO/IC heeft aanvullende bewijs gevraagd: De BA heeft een email (pag 26 post) gestuurd met de link bijgevoegd naar het gerealiseerde product (digitale Leefomgevignstoets). Wel een opmerking in rapport.\nKC03: Naam niet gelijk aan naam voorstel voor besluitvorming, maar wel gelijk aan 01 Rollen per afdeling per 22_10_2018.\nKC05 en KC06: Tarief is cf offerte. Overigens is in de offerte een plafondbedrag van �50.000 genoemd, waarbij wordt gefactuurd op basis van bestede tijd maal tarief (zie ook opmerking KC02c). Er was een raamcontract met RoyalHaskoning DHV echter deze liep tot 30 juni 2018, terwijl de activiteiten van het besluit in de steekproef betrekking hebben op de periode juli tm december. Op dit moment is Bureau Inkopen bezig met de nieuwe aanbesteding (verwacht dat dit in de komende maanden wordt afgerond). Omdat het bedrag van het besluit onder de �50k was is de opdracht enkelvoudig ingekocht. Totale verplichting voor Omgevingsbeleid is �140k, onder aanbestedingsgrens.\n",
    Controleur: "Shenita"
  },
  {
    _id: 4,
    PostNr: 4,
    OrganisatieEenheid: "DBI",
    Afdeling: "Dienst Beheer Infrastructuur",
    Bureau: "Eenheid DBI",
    Kostenplaats: 460,
    DocumentNummer: 294078,
    LeverancierInkoopOmschrijving:
      "STEDIN NETBEHEER B.V.\n\nVerzamelfactuur elektriciteit juni 2018 voor steunpunten, beweegbare kunstwerken, bewegwijzering, openbare verlichting en verkeerslichten van de dienst beheer infrastructuur.\n\nPZH_2017_634069496",
    BedragFactuur: " � 2.348,90 ",
    BedragBesluit: " � 67.000 ",
    SoortInkoop: "Levering",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "ja",
    KC3: "ja",
    KC4: "n.v.t.",
    KC5: "ja",
    KC6: "n.v.t.",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "n.v.t.",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "KC01: PHZ_nummer niet vermeld op factuur. Gesproken op 21_1_2019 met Aat van Ek, hij geeft aan dat de facturen van Stedin transportkosten van energie betreffen. Dit zijn verplichte kosten en zijn een gevolg van de energiecontracten. Er is dan ook geen apart contract met Stedin aanwezig.\nKC02a: Pommer van factuur is niet gelijk aan voorstel voor besluitvorming maar dit wordt veroorzaakt doordat de originele pommer een andere functie heeft gekregen en dus is vervangen; zie uitleg behandelend ambtenaar.Akkoord.\nDe pommer stelt vast dat het adres dat gefactureerd wordt een PZH en DBI locatie is. Hiervan wordt geen vastlegging gemaakt. Er wordt door de Pommer geen controle uitgevoerd op de tarieven en verbruik. De pommer wel een overzicht bij van de kosten per maand per locatie, waardoor op zn minst een plausibiliteitscontrole mogelijk is (en bij bijzonderheden een uitgebreidere controle uitgevoerd kan worden danwel navraag bij de leverancier gedaan kan worden. AO/IC heeft aanvullende zekerheid gevraagd: op verzoek voor 5 locaties vastgesteld dat eancode is opgenomen in dbenergie.nl. Tevens voor 1 levering vastgesteld dat de tarieven overeenkomen met de tarieven op de website van Stedin. \nSM: Gesproken met Aat van Ek (Contractmanager) op 21_1_2019: hij geeft aan dat er een aanvullende controle wordt uitgevoerd door Trenton (een bedrijf dat gespecialiseerd is in controles van energiecontracten). Op dit moment stellen zij vast of de gefactureerde eancode op naam staat van PZH en of de juiste belastingcluster (tarief) wordt toegepast.Hierover wordt jaarlijks gerapporteerd; het rapport over 2018 is nog niet ontvangen. Aat van Ek heeft de energiecontracten sinds vorig jaar in beheer en is op dit moment bezig de controle op de contracten te verscherpen. Eerste punt die hierbij wordt opgepakt, is het in kaart brengen van de objecten en bijbehorende contracten, daarnaast gaat er een nieuwe aanbesteding plaatsvinden. Als dit is gedaan zal er worden gekeken of Trenton ook een trendanalyse kan uitvoeren op hrt verbruik. Dus ondanks dat de controle door de pommer niet op alle aspecten wordt uitgevoerd, wordt het risico door aanvullende werkzaamheden gemitigeerd.\nKC03: Naam niet gelijk aan naam voorstel voor besluitvorming, maar wel gelijk aan 01 Rollen per afdeling per 22_10_2018.\nKC04: Geen inkoopplan aanwezig. Betreft de inkoop van energie welke via raamcontracten loopt en waarvan de verplichting 2018 via een AAA37 besluit is vastgelegd, derhalve inkoopplan niet van toepassing.\nKC05: Er is geen raamcontract met Stedin omdat het hier gaan om wettelijk geregelde transportkosten voor energie.\nKC08: De kosten zijn geboekt op kostenplaats 464, het besluit is getekend door bureauhoofd van kostenplaats 464.\nKC07 tm KC12: Betreft een uitvraag binnen de raamovereenkomst derhalve geen Besluit tot machtiging aanbesteding niet verplicht. \nKC13: Twee verplichtingen aangemaakt op 1 besluitnota, totaalbedrag verplichtingenadministratie is hoger dan bedrag op voorstel voor besluitvorming. Dit wordt veroorzaakt doordat de pommer gedurende het jaar is gewijzigd. Vastgesteld aan de hand van rapport verplichtingen 2014_2025 dat het totaal van de ontvangen facturen en lopende verplichting 2018 aansluit op het voorstel voor besluitvorming.",
    Controleur: "Shenita"
  },
  {
    _id: 5,
    PostNr: 5,
    OrganisatieEenheid: "DRM",
    Afdeling: "Projecten en Programma's",
    Bureau: "Projecten en Programma's II",
    Kostenplaats: 48,
    DocumentNummer: 292852,
    LeverancierInkoopOmschrijving:
      "LOUIS BOLK INSTITUUT\n\nBuijtenland van Rhoon\n\nPZH_2018_635599474",
    BedragFactuur: "38079,59",
    BedragBesluit: "77480",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "ja",
    KC3: "ja",
    KC4: "ja",
    KC5: "open",
    KC6: "ja",
    KC7_1: "nee",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "ja",
    KC10_1: "n.v.t.",
    KC10_2: "ja",
    KC11_1: "n.v.t.",
    KC11_2: "ja",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "n.v.t.",
    Opmerkingen:
      'KC02: De pommer heeft een mail gestuurd naar de projectleider voor de prestatiebeoordeling. De projectleider geeft aan dat hij de prestatie beoordeeld op basis van de gewerkte uren, echter hiervan is geen vastlegging (geen getekende urenbriefjes oid). Daarnaast wordt verwezen naar de eindrapportage voor de prestatiebeoordeling (zie http://idms/otcs/llisapi.dll/properties/PZH_2018_655881561). Opmerking in rapport\nKC03: Volgens document "102 Lijst van ambtelijk opdrachtgevers en opdrachtgevers van concernopgaven per maart 2018" (zie ACD) is Raymond Manger bevoegd tot autorisatie van Buijtenland van Rhoon.\nKC05: NIET AKKOORD. Uit rapport verplichtingen blijkt dat het totaal aan verplichtingen voor PKB_doelen voor Buijtenland van Rhoon boven de aanbestedingsgrens ligt. De behandelend ambtenaar geeft aan dat dit pas bij het verstrekken van de laatste opdracht (van �124k) duidelijk werd en ook niet in een eerder stadium voorzienbaar was. Gezien de ervaring die reeds was opgedaan door LBI en het feit dat de laatste verplichting aansluit op de overige werkzaamheden, was het niet verstandig om de opdracht europees uit te besteden. Daarnaast is dit allemaal een tijdelijke oplossing totdat de CooperatieBuijtenland van Rhoon van start gaan (halverwege 2018). Uiteindelijk onderkent de behandelend ambtenaar dat de uitvraag niet de aanbestedingsregels hebben gevolgd, maar dat dit zo een specifieke situatie was dat er ook geen optie was om voor een andere leverancier te kiezen. Deze standpunt is ook bevestigd door Dennis Rozema (Senior beleidsmedewerker FJZ). In dit geval had dan ook mijn inziens een aanbestedingsjurist geconsulteerd moeten worden bij de besluitvorming, zodat deze een uitspraak had kunnen doen over het afwijken van de aanbestedingsregels. Uit de workflow blijkt dat een financieel adviseur, een juridisch adviseur en medewerker BIR is geconsulteerd voor het besluit in de steekproef. Uit de workflow blijkt niet dat er door de adviseurs vragen is gesteld over de enkelvoudige inkoopprocedure danwel dat zij het niet eens zijn met het volgen van een enkelvoudige inkoopprocedure. Bij de vervolgbesluiten (besluit 3 en 4) is geen advies ingewonnen bij FJZ/BIR/K&C. TdG 25/1: openstaand punt:  \nDe wijze waar op de opdrachten zijn aanbesteed, met de bijbehorende argumantatie en de wijze hoe het geheel is verlopen wordt eerste nader besproken met de aanbestedingsjurist. Daarna wordt dit voorgelegd en besproken met het verantwoordelijk bureauhoofd. De bevindingen en bijbehorende risico�s en indien van toepassing de gevolgen voor onrechtmatigheid ihkv de JR worden dan nauwkeurig bepaald en gedeeld met de accountant.\nKC06: Bedrag cf inkoopplan en offerte.\nKC07: NIET AKKOORD. Er is geen besluit tot machting inkoop opgesteld omdat dit een vervolgbesluit is. Afgestemd met PL die dat onderkent en als toelichting geeft dat deze stap geen meerwaarde had omdat er al een besluit was genomen door de ambtelijk opdrachtnemer dat de leverancier om het werk uit te laten voeren.Echter er is ook geen besluit tot machtiging inkoop gevonden voor originele besluit.',
    Controleur: "Shenita"
  },
  {
    _id: 6,
    PostNr: 6,
    OrganisatieEenheid: "DBI",
    Afdeling: "Dienst Beheer Infrastructuur",
    Bureau: "Eenheden DBI",
    Kostenplaats: 458,
    DocumentNummer: 295111,
    LeverancierInkoopOmschrijving:
      "POSG PROFESSIONALS B.V.\n\nLoopbaancoaching. Individueel overeenkomst 100A00489 Klein Klouwenberg 1_8_2018 t/m 30_4_2019\n\nPZH_2018_659421021",
    BedragFactuur: "8850,00",
    BedragBesluit: "8850",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "ja",
    KC3: "ja",
    KC4: "n.v.t.",
    KC5: "ja",
    KC6: "ja",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "ja",
    KC10_1: "n.v.t.",
    KC10_2: "ja",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "KC02: Er is geen separate onderbouwing van de presentatie, aangezien het gaat om een contractueel overeengekomen vergoeding voor loopbaanontwikkeling voor de periode 1 augustus 2018 tot en met 30 april 2019.\nKC03: Naam niet gelijk aan naam voorstel voor besluitvorming, maar wel gelijk aan 01 Rollen per afdeling per 22_10_2018.\nKC04: Geen inkoopplan aanwezig. Betreft geen reguliere inkoop, het gaat hier om de facturatie als gevolg van de overname van een medewerker van PZH. Trigger voor de aankoop is de vaststellingsovereenkomst waarin is overeengekomen dat de medewerker uitdienst zal treden bij PZH en indienst zal treden van POSG. De factuur betreft een bedrag voor loopbaancoaching.\nKC05: Betreft de overname van een medewerker door POSG. Voor deze diensten was een raamcontract met POSG overeengekomen, echter deze liep tot 30 november 2016. Nadien geen raamcontract meer uitgevraagd. Een analyse uitgevoerd op de verplichtingen tot heden, hieruit blijkt dat er van 1 januari 2017 tot nu een verplichting is aangegaan bij POSG van ongeveer �170k (excl. de loonsomkosten). Dit is doorgegeven aan bureau Inkoop (Johan Remijnse) ter overweging om een raamcontract uit te vragen. \nKC06: Bedrag is conform voorstel voor besluitvorming en offerte. Er wordt in de voorstel voor besluitvorming gerefereerd naar een raamovereenkomst, deze is echter niet meer geldig vanaf 30 november 2016..\nKC08: Volgens 01 Rollen per afdeling is de afdelingshoofd bevoegd om het besluit te tekenen. Echter in dit geval is het besluit getekend door bureauhoofd (van kostenplaats 459, factuur is geboekt op kostenplaats 458). Dit nagevraagd bij het afdelingshoofd en tekenende bureauhoofd, die geven aan dat het bureauhoofd de proxy heeft gekregen gedurende de vakantie van het afdelingshoofd. Het gaat om een AAA16_besluit, dat door een bureauhoofd getekend mag worden.\nKC09 en KC10: Zowel financieel en juridisch adviseur geraadpleegd, deze waren beide akkoord zonder opmerkingen derhalve geen aanpassing door behandelend ambtenaar noodzakelijk.\nKC11 en KC12: Het betreft kosten voor loopbaanbegeleiding zoals overeengekomen in vaststellingsovereenkomst, derhalve geen advies van BIR of K&C noodzakelijk geacht.\nKC07 tm KC12: Bedrag onder �50k derhalve besluit tot machtiging tot aanbesteding niet verplicht.\nKC13: Totaalbedrag verplichtingenadministratie is hoger dan bedrag op voorstel voor besluitvorming. Dit wordt veroorzaakt doordat er een verschuiving heeft plaatsgevonden tussen 2018 en 2019 (zie uitleg medewerker crediteurenadministratie). Vastgesteld aan de hand van rapport verplichtinngen 2014_2025 dat het totaal van de ontvangen facturen en lopende verplichting aansluit op het voorstel voor besluitvorming.",
    Controleur: "Shenita"
  },
  {
    _id: 7,
    PostNr: 7,
    OrganisatieEenheid: "DRM",
    Afdeling: "Projecten en Programma's",
    Bureau: "Afdelingsleiding Projecten en Programma's",
    Kostenplaats: 44,
    DocumentNummer: 294196,
    LeverancierInkoopOmschrijving:
      "DHM\n\nInhuur Hielke van Ginkel als planner voor de periode 1 december 2017 t/m 31 december 2018 (kosten 2018 �156.798)\n\nPZH_2017_625184509",
    BedragFactuur: " � 9.790,11 ",
    BedragBesluit: " � 159.774 ",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "open",
    KC3: "ja",
    KC4: "ja",
    KC5: "ja",
    KC6: "ja",
    KC7_1: "nee",
    KC7_2: "ja",
    KC8_1: "nee",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "ja",
    KC10_1: "n.v.t.",
    KC10_2: "ja",
    KC11_1: "n.v.t.",
    KC11_2: "ja",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "nee",
    Opmerkingen:
      "KC02; TdG: Prestatie is geaccordeerd door het bureauhoofd die eveneens heeft beslist over de inkoop. In principe geen sprake van functiescheiding hetgeen niet als wenselijk wordt beschouwd. Openstaand punt: aanvullende informatie en stukken opvragen aan de prestatieverklaarder (in dit geval ook de beslisser) over de periode van de factuur.\nKC07: Geen besluit machtiging tot aanbesteden opgesteld. Besproken met Jeffrey Goyarts (Project Medewerker Bureau Integrale Projectbeheersing) en Zersenay Woldu (Project Medewerker Bureau Integraal Projectbeheersing): er is geen machtiging tot aanbesteding opgesteld omdat het besluit is genomen door het bureauhoofd welke ook tevens de beslisser is (zoals dit ook is gebeurd bij het voorstel voor besluitvorming; zie pagina 1). Dit wordt door de afdeling gezien als onlogisch. TdG: bevinding 'geen machtiging'  alleen meegenomen bij KC07. zie ook verdere opmerkingen in reviewformulier. \nKC08: Besluit is in eerste instantie geboekt op kostenplaats 044 (en later op basis van de urenstaat overgeboekt naar andere kosten plaatsen middels een IK_MEM). Het besluit is getekend door een budgethouder van andere afdelingen (Coen Glaser budgethouder voor kostenplaats 356/389/390/391/454/048/354); veel van deze kostenplaatsen zijn gebruikt voor het boeken van de correctie, dus waar uiteindelijk de kosten op geboekt zijn. Derhalve akkoord bevonden aangezien de kosten niet ten laste van 044 komen. TdG: de opmerking feit blijft dat het besluit gunning alleen een verplichting aangeeft voor de kostenplaats 044 en dit had door de juist bevoegde BH voor deze kosten moeten worden afgedaan. Dat naderhand kosten worden verdeeld naar andere kostenplaatsen betreft iets anders en gebeurt uiteraard vaker. Hoogstens een verzachtende omstandigheid dat de BH van de kostenplaats dit achteraf te zien krijgt. Derhalve KC op nee gezet.(nb de correctie naar ander kostenplaatsen blijkt ook niet geheel goed te gaan (zie KC16)\nKC09 tm 12:Verplichte consultatielijst afgeschaft per 1 mei 2017. Besluit is van december 2017.\nKC16: Correctie betreft een doorverdeling van de geboekte factuur op deelproduct 002059 naar de projecten waarop de uren zijn geschreven. De uren zijn in Sagitta geautoriseerd door het bureauhoofd. wat in dit geval volstaat als goedkeuring voor de correctie aangezien het ondoenlijk is om voor alle budgethouders waarop gecorrigeerd wordt een goedkeuring te vragen en uiteindelijk blijkt de goedkeuring dan ook uit de geautoriseerde uren. Ccorrectie is ten laste van de verkeerde kostenplaats geboekt (354, terwijl de factuur in eerste instantie is geboekt op kostenplaats 044), echter dit kan niet meer gewijzigd worden in verband met het sluiten van het boekjaar. Aangezien 354 onder organisatorisch onder 044 valt is de impact gering.",
    Controleur: "Shenita"
  },
  {
    _id: 8,
    PostNr: 8,
    OrganisatieEenheid: "DLB",
    Afdeling: "Samenleving & Economie",
    Bureau: "Bureau Economische Zaken",
    Kostenplaats: 396,
    DocumentNummer: 293801,
    LeverancierInkoopOmschrijving:
      "De Vink Communicatie\n\nwerkzaamheden juli 2018 tbv programma Circulaire Economie\n\nPZH_2018_635193720",
    BedragFactuur: "10062,36",
    BedragBesluit: "39744",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "open",
    KC3: "ja",
    KC4: "ja",
    KC5: "ja",
    KC6: "ja",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "n.v.t.",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "ja",
    Opmerkingen:
      "KC02: Openstaand punt: SM: Vragen aan Projectleider VRIES/KABEL GEMAILD OP 18_1_2019\nKC07 tm KC12: Verplichting is < �50k derhalve besluit machtiging aanbesteden niet van toepassing.\nKC09 tm 12:Verplichte consultatielijst afgeschaft per 1 mei 2017. Besluit is van 2018.\nKC16: Correctie is doorgegeven door A. Poppe (FJA). Besproken met Aad: bij aanvang van de werkzaamheden tbv circulaire economie was er nog geen deelcode (en budget) beschikbaar voor circulaire economie en zijn de kosten dus geboekt op een andere code. Deze is later toegekend (voor_ of najaarsnota). Later zijn de kosten voor circulaire economie dan ook overgeboekt naar de juiste deelcode. Dit is goedgekeurd door de budgethouder. \n",
    Controleur: "Shenita"
  },
  {
    _id: 9,
    PostNr: 9,
    OrganisatieEenheid: "DRM",
    Afdeling: "Projecten en Programma's",
    Bureau: "Bureau Projecten en Programma's III",
    Kostenplaats: 140,
    DocumentNummer: 282073,
    LeverancierInkoopOmschrijving:
      "Stal Langelaan\n\nKleinschalige maatregelen IODS (plaatsen vossenvallen en alarmen)\n\nPZH_2017_625688971",
    BedragFactuur: "1650,00",
    BedragBesluit: "1650",
    SoortInkoop: "Levering",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "ja",
    KC3: "ja",
    KC4: "ja",
    KC5: "ja",
    KC6: "ja",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "open",
    KC9_1: "n.v.t.",
    KC9_2: "n.v.t.",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "ja",
    Opmerkingen:
      "KC07 tm KC12: Verplichting is < �50k derhalve besluit machtiging aanbesteden niet van toepassing.\nKC08: Besluit is getekend door Hans Kleij Programmamanager Bureau Projecten en Programmas III) echter op het ondermandaatoverzicht (zie http://idms/otcs/llisapi.dll/link/617201671) staat dat Donald Broekhuizen (senior projectleider B Bureau Porjecten en Programmas III) bevoegd is voor IODS. Dit nagevraagd bij de behandelend ambtenaar en die geeft aan dat naar zijn idee Hans Kleij altijd bevoegd is geweest voor IODS, hij kan hiervan echter geen bewijs (getekende mandaat oid) overleggen. Dit ook besproken met Remco van Halen (coordinator juridisch beleid) die geeft ook aan geen ondermandaat ontvangen te hebben voor Hans Kleij. Tevens geeft Remco aan dat het ondermandaatoverzicht door hen is opgesteld op basis van de bij hem beschikbare informatie, dit hoeft dus niet perse de laatse/juiste weergave van de werkelijkheid te zijn. TdG 24/1: openstaand punt: eerst nader onderzoeken en afstemmen met Hans Kleij, mede omdat de BA aangeeft dat Hans altijd bevoegd is geweest. Dus wellicht zijn er veel meer besluiten. \nKC09 tm 12:Verplichte consultatielijst afgeschaft per 1 mei 2017. Besluit is van november 2017.\nKC16: Akkoord. betreft overboeking van grootboekrekening 47301 (Exploitatieprojecten (aank.grond)) naar 47305 (Expl.proj.(aank.niet duurz.goed/dns)). Advies JFA gevraagd, goedkeuring niet noodzakelijk geacht cf werkafspraken (zie ACD 11 Procedure memoriaal boekingen).\n",
    Controleur: "Shenita"
  },
  {
    _id: 10,
    PostNr: 10,
    OrganisatieEenheid: "DBI",
    Afdeling: "Dienst Beheer Infrastructuur vanaf 2018",
    Bureau: "Eenheid DBI vanaf 2018",
    Kostenplaats: 462,
    DocumentNummer: 281501,
    LeverancierInkoopOmschrijving:
      "Movares\n\nInhuur AP van Vugt als projectleider betontechnisch onderhoud voor de periode 1 december 2016 tm 1 december 2018 (kosten 2018 �82.720)\n\nPZH_2016_572267383",
    BedragFactuur: " � 14.423,20 ",
    BedragBesluit: " � 180.480 ",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "ja",
    KC3: "ja",
    KC4: "n.v.t.",
    KC5: "ja",
    KC6: "ja",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "ja",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "ja",
    KC12_1: "n.v.t.",
    KC12_2: "ja",
    KC13: "ja",
    KC14: "n.v.t.",
    KC15: "ja",
    KC16: "ja",
    Opmerkingen:
      "KC02: Prestatie vaststelling op basis van getekende urenstaten\nKC04: Geen inkoopplan aanwezig. Dit besproken met Josje van Eijk_Selman (Contractbeheerder Bureau Inkoop), zij geeft aan dat het opstellen van een inkoopplan niet verplicht is bij een uitvraag binnen een DAS. Indien er een verlening plaatsvindt van de opdracht, moet er wel een inkoopplan opgesteld worden hiervoor. Vastgesteld dat er wel een inkoopplan voor de verlenging op IDMS staat.\nKC05 en KC06: Opdracht is via DAS inhuur Technisch gerelateerd personeel uitgevraagd.\nKC07 tm KC12: Geen besluit tot machtiging aanbesteding opgesteld. De vakafdeling geeft hier als verklaring voor dat dit pas van toepassing is voor veplichtingen boven de aanbestedingsgrens. Dit tevens besproken met Josje van Eijk_Selman (Contractbeheerder Bureau Inkoop), zij bevestigt dat er geen machtiging aanbesteding nodig is bij een uitvraag binnen de DAS. TdG; zie opmerkingen reviewformulier.\nKC09 tm KC12: Advies cf consultatielijst niet verplicht bij uitvraag binnen ROVK/DAS. Er is wel geconsulteerd bij Bill Wouters (F_adviseur), Diana Vrijenhoek (BIR) en Jan Verhoeven (Jurist K&C). \nKC13: Er is een nieuwe verplichting aangemaakt omdat de pom gedurende 2018 is overgezet naar een andere medewerker. Daarnaast een nieuwe verplichting aangemaakt in verband met gewijzigde kostenplaats.\nKC14: De kostenplaats in CODA komt niet overeen met de kostenplaats in het voorstel voor besluitvorming. Uiteindelijk zijn alle kosten op verplichting 154227 alsnog, middels IK_MEM5513, overgeboekt naar kostenplaats EN0001701 (deze kostenplaats is ook niet conform voorstel voor besluitvorming). Zie verder KC16.\nKC16: Correctie is goedgekeurd door budgethouder.",
    Controleur: "Shenita"
  },
  {
    _id: 11,
    PostNr: 11,
    OrganisatieEenheid: "DCZ",
    Afdeling: "Facilitaire Zaken",
    Bureau: "Catering, Evenementen, AV, Loket en Wagenpark",
    Kostenplaats: 369,
    DocumentNummer: 908291,
    LeverancierInkoopOmschrijving:
      "Leaseplan\n\nTussentijdse afrekening brandstofkosten 3 Priussen\n\nPZH_2017_582525830",
    BedragFactuur: "5092,48",
    BedragBesluit: "152146",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "ja",
    KC3: "ja",
    KC4: "ja",
    KC5: "ja",
    KC6: "n.v.t.",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "ja",
    KC10_1: "n.v.t.",
    KC10_2: "ja",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "De factuur heeft betrekking op verschillende besluiten, aangezien de selectie betrekking heeft op de boeking van de Priussen, heb ik enkel het besluit horende bij de Pruissen beoordeeld.\nKC01a Tarief: n.v.t. aangezien het gaat om een afrekening van brandstofkosten welke plaatsvind op basis van werkelijk gemaakte kosten.\nKC02: Van de factuur wordt vastgesteld dat de kentekens conform overeenkomst zijn. Er vind verder een plausibiliteitscontrole plaats op het verbruik, meer is ook niet mogelijk.\nKC06: Factuur betreft een afrekening voor benzinekosten, hiervoor wordt maandelijks een voorschotbedrag in rekening gebracht en achteraf worden\nKC03 en KC14: Eind 2017/begin 2018 is wagenparkbeheer binnen Facilitaire zaken omgehangen van een andere kostenplaats tot gevolg heeft gehad. Hierdoor komt de kostenplaats in CODA niet overeen met de kostenplaats genoemd in de voorstel voor besluitvorming.\nKC05: n.v.t. factuur valt onder raamcontract met Leaseplan.\nKC07 tm KC12: Betreft een factuur binnen een raamovereenkomst derhalve besluit machtiging tot aanbesteding niet van toepassing.\nKC13: Nieuwe verplichting aangemaakt omdat halverwege het jaar de pommer is gewijzigd. Akkoord.\nKC16: Niet van toepassing, het gaat hier niet om een correctie maar een creditfactuur, derhalve geen aanvullende werkzaamheden noodzakelijk.",
    Controleur: "Shenita"
  },
  {
    _id: 12,
    PostNr: 12,
    OrganisatieEenheid: "DCZ",
    Afdeling: "Informatisering en Automatisering",
    Bureau: "Infrastructuur & Support",
    Kostenplaats: 279,
    DocumentNummer: 287044,
    LeverancierInkoopOmschrijving: "KPN\n\nKosten Zakelijk Internet mei 2018",
    BedragFactuur: "8041,60",
    BedragBesluit: " n.v.t. ",
    SoortInkoop: "Dienst",
    SoortFactuur: "Direct",
    KC1: "nee",
    KC2: "nee",
    KC3: "ja",
    KC4: "n.v.t.",
    KC5: "n.v.t.",
    KC6: "n.v.t.",
    KC7_1: "n.v.t.",
    KC7_2: "n.v.t.",
    KC8_1: "n.v.t.",
    KC8_2: "n.v.t.",
    KC9_1: "n.v.t.",
    KC9_2: "n.v.t.",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "n.v.t.",
    KC14: "ja",
    KC15: "ja",
    KC16: "ja",
    Opmerkingen:
      "KC01 (n.v.t.bij KC04 en KC06): NIET AKKOORD. Bedrag groter dan �1,500, daarnaast betreft dit maandelijks terugkerende kosten, derhalve had er een besluit aangemaakt moeten worden. Dit besproken met Henk van Broeckhuijsen (senior adviseur I&A); het betreft een factuur voor ADSL_lijnen bij KPN. Het reguliere internetcontract loopt via Axians; hiervoor is een europese aanbesteding geweest. Echter een aantal PZH locaties zijn alleen via ADSL te bereiken waardoor deze lijnen bij KPN (de oude raamcontract partij) zijn gebleven en deze lijnen zullen op termijn vervangen moeten worden door andere oplossingen. Om deze reden is er dit moment ook geen geldige (raam)contract voor deze ADSL_lijnen. Er is ook geen besluit aangemaakt voor het vastleggen van de kosten/verplichting 2018; dit zal naar aanleiding van deze controle vanaf 2019 wel gebeuren.\nKC01a/KC03a: Kostenplaats niet vermeld op factuur. Dit komt omdat de factuur meerdere kostenplaatsen betreft, welke vervolgens via memoriaalboeking (ME_TEL) wordt overgeboekt naar de juiste kostenplaatsen (voor de afdeling waar de kosten zijn gemaakt).\nKC02: NIET AKKOORD, de directe factuur wordt goedgekeurd door budgethouder (Arjan Boere). Hierbij vindt geen controle op prestatie plaatst (er wordt er niet gecheckt of de gefactureerde locaties, PZH locaties zijn met een ADSL_lijn via KPN). Wel worden de kosten overgeboekt middels een Calvi bestand (bestand waarin per lijn wordt bijgehouden voor welke afdeling de lijn is) naar het juiste grootboekrekening en kostenplaats (waarna de tusserekening dus glad zou moeten lopen). Echter ook dit is in de afgelopen jaren niet goed gedaan wat heeft geresulteerd in een afboeking in 2018. Ook dit proces zal in 2019 worden herzien. TdG 25/1: openstaand punt: nog terugkoppeling  per mail van afspraken en om voor deze factuur aantoonbaar bewijs van prestatie (p&q) aan te leveren teneinde meer zekerheid te verkrijgen.\nKC04 en KC06: deze op nvt gezet. De bevinding is opgenomen bij KC01. \nKC16: Telefonie facturen worden in eerste instantie op 1 kostenplaats geboekt, vervolgens worden aan de hand van een bestand van I&A de kosten overgeboekt naar de betreffende afdeling waar de kosten gemaakt worden. Hiervoor geen goedkeuring van budgethouders of JFA voor nodig.\nKC07 tm KC12: Verplichting is < �50k derhalve besluit machtiging aanbesteden niet van toepassing vwb gunning: De bevinding is opgenomen bij KC01. ",
    Controleur: "Shenita"
  },
  {
    _id: 13,
    PostNr: 13,
    OrganisatieEenheid: "DRM",
    Afdeling: "P&P",
    Bureau: "Project Rijnland Route",
    Kostenplaats: 432,
    DocumentNummer: 292210,
    LeverancierInkoopOmschrijving:
      "C024516 _ Comol5\n\nN206 Rijlandroute _ gunning contractdeel A44_N434_A4",
    BedragFactuur: "5882359,56",
    BedragBesluit: "492 mln",
    SoortInkoop: "Werk",
    SoortFactuur: "Match",
    KC1: "Ja",
    KC2: "Ja",
    KC3: "N.v.t.",
    KC4: "Ja",
    KC5: "N.v.t.",
    KC6: "Ja",
    KC7_1: "Ja",
    KC7_2: "Ja",
    KC8_1: "Ja",
    KC8_2: "Ja",
    KC9_1: "Ja",
    KC9_2: "Ja",
    KC10_1: "n.v.t.",
    KC10_2: "Ja",
    KC11_1: "Ja",
    KC11_2: "Ja",
    KC12_1: "Ja",
    KC12_2: "Ja",
    KC13: "Ja",
    KC14: "Ja",
    KC15: "Ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "KC2a: pommer verplichting wijkt van pommer op besluit. Verklaring: Sharida heeft deze taak van Angela overgenomen (mail p.142). Betreft overigens niet meer dan een administratieve rol: de prestatieverklaring wordt door de projectleider gedaan.\nKC2b en c: Factuur voor akkoord getekend door contractbeheerder PZH H. Berkhout (p. 145). Zie apart opgeslagen bestanden voor de onderbouwing van de pom. Termijnstaat is gecontroleerd door assistent contractmanager P. de Bruijne (zie mail met cc aan Berkhout; bestand pom 01). Zichtbare controle: bestand pom 02. Aanvulllende bijlagen bij termijnstaat: voortgang projectplanning (bestand pom3) en 'betaalpost werkpakket': pom4.\nKC3: n.v.t. Betreft matchfactuur. De budgethouder heeft geen rol in het proces van matchfacturen.\nKC4: Gezien complexiteit project bestaat Inkoopplan uit 12 bestanden, zie http://idms/otcs/llisapi.dll/open/531721154. Deze bestanden zijn geraadpleegd voor de beantwoording van KC4.\nKC5: n.v.t. Betreft EU aanbesteding.\nKC10_1: n.v.t. Art 11 (ACD03/01) is van toepassing en hierbij hoeft er geen J advies te worden geraadpleegd, dit is ook niet gevraagd.",
    Controleur: "Remco"
  },
  {
    _id: 14,
    PostNr: 14,
    OrganisatieEenheid: "DBI",
    Afdeling: "DBI",
    Bureau: "Projecten DBI",
    Kostenplaats: 465,
    DocumentNummer: 295605,
    LeverancierInkoopOmschrijving: "Arcadis\n\nEngineering grootonderhoud N486",
    BedragFactuur: "15.683,00",
    BedragBesluit: " � 492.000 ",
    SoortInkoop: "Werk",
    SoortFactuur: "Match",
    KC1: "Ja",
    KC2: "Ja",
    KC3: "N.v.t.",
    KC4: "Ja",
    KC5: "N.v.t.",
    KC6: "Ja",
    KC7_1: "n.v.t.",
    KC7_2: "Ja",
    KC8_1: "n.v.t.",
    KC8_2: "Ja",
    KC9_1: "n.v.t.",
    KC9_2: "Ja",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "Ja",
    KC12_1: "n.v.t.",
    KC12_2: "Ja",
    KC13: "Ja",
    KC14: "Ja",
    KC15: "Ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "KC2b en c: pom is in CODA gezet door Kees Bergen, projectleider. Deze heeft ook de prestatie vastgesteld. Kees heeft mondeling toelichting gegeven op de belangrijkste onderdelen van de termijnstaat en op ons verzoek onderbouwingen aangeleverd. Zie termijnstaat (p. 2 t/m 4) voor deze toelichtingen. Onderbouwende documenten zijn apart opgeslagen. Akkoord.\nKC3: n.v.t. Betreft matchfactuur. De budgethouder heeft geen rol in het proces van matchfacturen.\nKC5: n.v.t. Betreft ROVK.\nKC13a: Verplichting 2018 in CODA wijkt af van verplichting 2018 op VVB. Reden: verplichtingen 2016 en 2017 zijn niet volledig gepomd en deels overgehelveld naar 2018. Daarnaast is op verzoek vakafdeling de verplichting 2019 ook naar 2018 overgeheveld. Zie aanvullende toelichting in documentatie.\nKC 07_1, 08_1 etc: n.v.t. Geen machtiging aanbesteding van deze opdracht, betreft ROVK.\nKC10_2: n.v.t. Art 11 (ACD03/01) is van toepassing en hierbij hoeft er geen J advies te worden geraadpleegd, dit is ook niet gevraagd.\nKC12_2: artikelen in oud cons lijst zijn n.v.t. voor ROVK'en. Er is wel K&C advies gevraagd, dit is beoordeeld, geen bevindingen.",
    Controleur: "Remco"
  },
  {
    _id: 15,
    PostNr: 15,
    OrganisatieEenheid: "DCZ",
    Afdeling: "I&A",
    Bureau: "Portfoliomanagement",
    Kostenplaats: 277,
    DocumentNummer: 294986,
    LeverancierInkoopOmschrijving: "Topdesk\n\n12 dagen consultancy",
    BedragFactuur: "1190,00",
    BedragBesluit: " xx ",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "Ja",
    KC2: "Open",
    KC3: "N.v.t.",
    KC4: "Ja",
    KC5: "N.v.t.",
    KC6: "Ja",
    KC7_1: "n.v.t.",
    KC7_2: "Ja",
    KC8_1: "n.v.t.",
    KC8_2: "Ja",
    KC9_1: "n.v.t.",
    KC9_2: "Ja",
    KC10_1: "n.v.t.",
    KC10_2: "Ja",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "Ja",
    KC14: "Ja",
    KC15: "Ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "KC2b en c: betreft 12 dagen strippenkaart voor diensten Topdesk consultant. Gefactureerd is ��n dag, datum is niet vermeld, wel periode van 1,5 week waarbinnen deze dag valt. Pommer Petra Kok heeft presatie niet vastgesteld, dit is Mark Bosma geweest. Ik heb hem gevraagd 1) hoe de prestatie is vastgesteld 2) hoe zich wordt gehouden op niet overschrijden van de 12 dagen termijn. Gevraagd om uiterlijk morgen te reageren. Vandaag (25_1) zal ik nog even bellen Openstaand punt\nKC3: n.v.t. Betreft matchfactuur. De budgethouder heeft geen rol in het proces van matchfacturen.\nKC5: n.v.t.. Betreft ondersteuning voor Topdesk software door de leverancier van Topdesk. Deze ondersteuning kan niet door een andere leverancier plaatsvinden, cf melding in inkoopplan (p. 20). EU aanbesteding van deze dienst is niet mogelijk.\nKC 07_1, 08_1 etc: n.v.t. Geen machtiging aanbesteding, betreft opdracht < 50k.\nKC10_2: Akkoord.  art 1 en 11 oud cons lijst (ACD03/01) zijn n.v.t. dus geen J advies, er is toch J advies gevraagd cf interne afspraak bij DCZ (J advies bij alle besluiten).\nKC11_2: n.v.t.  artikelen oude cons lijst (ACD03/01) zijn n.v.t. dus geen BIR advies verplicht, dit is ook niet gevraagd.\nKC12_2: artikelen in oude cons lijst (ACD03/01) zijn n.v.t. en er is ook geen K&C advies gevraagd.",
    Controleur: "Remco"
  },
  {
    _id: 16,
    PostNr: 16,
    OrganisatieEenheid: "DBI",
    Afdeling: "DBI",
    Bureau: "Projecten DBI",
    Kostenplaats: 465,
    DocumentNummer: 288899,
    LeverancierInkoopOmschrijving:
      "Centraal Beheer Achmea\n\n2e verlenging CAR verzekering",
    BedragFactuur: "2117,50",
    BedragBesluit: " xx ",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "Ja",
    KC2: "Ja",
    KC3: "N.v.t.",
    KC4: "N.v.t.",
    KC5: "Ja",
    KC6: "Ja",
    KC7_1: "n.v.t.",
    KC7_2: "Ja",
    KC8_1: "n.v.t.",
    KC8_2: "Ja",
    KC9_1: "n.v.t.",
    KC9_2: "n.v.t.",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "Ja",
    KC14: "Ja",
    KC15: "Ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "Betreft 2e verlenging CAR (Construction All Risk) verzekering. Deze beschermt de koper of opdrachtgever tijdens de verbouwing tegen schade aan bijv. bouwmaterialen. Verzekering is in 2016 afgesloten (PZH_2016_575976168) en 2x verlengd tm 2018. Alleen het besluit voor de 2e verlenging is gecontroleerd.\nKC2b en c: prestatievaststelling n.v.t. Betreft verzekeringspremie.\nKC3: n.v.t. Betreft matchfactuur. De budgethouder heeft geen rol in het proces van matchfacturen.\nKC4 n.v.t. Betreft 2e verlenging verzekering uit 2016. Voor een verlenging wordt geen inkoopplan opgesteld.\nKC5 Voorlopig Akkoord. Op regelmatig terugkerende diensten is art 2.21 Aanbestedingswet 2012 van toepassing. Deze Zie info in dossier voor meer info (p 47. Nieuwe actie: bepalen totale opdrachtwaarde CAR verzekeringen voor alle verzekeraars in de afgelopen 4 jaar (niet alleen CB Achmea), op advies van bureau Inkoop en aanbestedingsjurist. Uitvoering 25_1. Er is vooralsnog geen aanleiding om aan te nemn dat de EU grens is overschreden. Openstaand punt voor aanvullende actie.\nKC 07_1, 08_1 etc: Machtiging aanbesteden n.v.t.betreft opdracht < 50k. Oospr opdrachtwaarde 2016 � 2,5k (p. 8).\nKC7_2b akkoord (cf kruisjeslijst in Ondermandaatbesluit secretaris 2017 is het laagst toegestane niveau van ondermandaat AAA16a: directeurniveau. Dit wijkt af van VVB waarop bureauhoofd getekend heeft. Azad Iilahibas (WF specialist DBI) heeft toegelicht dat de kruisjeslijst niet goed is. DBI had in 2017 een AAA16 en een AAA16a mandaat. AAA16 geldt voor de directeur. Dit staat precies andersom in de kruisjeslijst. Ik verbind er geen gevolg aan. Proces is van 2017 en mandaat AAA16a is inmiddels afgeschaft dus een risico kan zich niet meer voordoen. Er is op het juiste niveau getekend.\nKC9_2: n.v.t. Opdracht < � 50k dus niet verplicht cf oude cons lijst, en ook niet gevraagd.\nKC10_2: n.v.t. Cf oude cons lijst art 11 (ACD03/01) hoeft geen J advies te worden, ook niet gevraagd.\nKC11_2: n.v.t.  artikelen oude cons lijst (ACD03/01) zijn n.v.t. dus geen BIR advies verplicht, dit is ook niet gevraagd.\nKC12_2: artikelen in oude cons lijst (ACD03/01) zijn n.v.t. en er is ook geen K&C advies gevraagd.",
    Controleur: "Remco"
  },
  {
    _id: 17,
    PostNr: 17,
    OrganisatieEenheid: "DRM",
    Afdeling: "P&P",
    Bureau: "Project Rijnland Route",
    Kostenplaats: 432,
    DocumentNummer: 296776,
    LeverancierInkoopOmschrijving:
      "Comol5\n\nAanvullende opdracht VTW0019a binnen project\nN206 Rijlandroute",
    BedragFactuur: "52.342,20",
    BedragBesluit: " xx ",
    SoortInkoop: "Werk",
    SoortFactuur: "Match",
    KC1: "Ja",
    KC2: "Ja",
    KC3: "N.v.t.",
    KC4: "Ja",
    KC5: "N.v.t.",
    KC6: "Ja",
    KC7_1: "Zie post 13",
    KC7_2: "Ja",
    KC8_1: "Zie post 13",
    KC8_2: "Ja",
    KC9_1: "Zie post 13",
    KC9_2: "Ja",
    KC10_1: "Zie post 13",
    KC10_2: "n.v.t.",
    KC11_1: "Zie post 13",
    KC11_2: "Ja",
    KC12_1: "Zie post 13",
    KC12_2: "Ja",
    KC13: "Ja",
    KC14: "Ja",
    KC15: "Ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "NB betreft aanvullende opdracht binnen EU aanbesteed project Rijnlandroute. Op de factuur staan drie bedragen 1) gerelateerd aan oorspr opdracht 2) aanvullend werk 1 en 3) aanvullend werk 2. In overleg met Ton heb ik het gunningsbesluit van de hoogste aanvullende opdracht gecontroleerd. De machtiging tot aanbesteden + gunning project RLR is al gecontroleerd bij post 13.\nKC2b en c: Factuur voor akkoord getekend door contractbeheerder PZH H. Berkhout (p. 33). Zie apart opgeslagen bestanden voor de onderbouwing van de pom. Termijnstaat is gecontroleerd door assistent contractmanager P. de Bruijne (zie mails met cc aan Berkhout; bestand 'pom 01'). Controle leverde twee punten op die zijn teruggekoppeld aan leverancier. Deze hebben betrekking op een onjuiste startdatum van een activiteit en een onjuiste indexering van aanvullende werk. De leverancier geeft aan akkoord te zijn met beide punten.Termijnstaat die gecontroleerd is: bestand 'pom 02'. Aanvulllende bijlagen bij termijnstaat gebruikt bij presatievaststelling: voortgang projectplanning ('pom3') en 'betaalpost werkpakket': 'pom4'.\nKC3: n.v.t. Betreft matchfactuur. De budgethouder heeft geen rol in het proces van matchfacturen.\nKC5 n.v.t. Betreft aanvullende opdracht binnen een EU aanbesteding. \nKC9 Financieel adviseur is niet geraadpleegd, echter niet verplicht. Cf voorwaarden oude consultatielijst zou advies verplicht zijn. Na inhoudelijke controle besluit heb ik geen fouten aangetroffen die een F_adviseur eruit had gehaald. Ik heb alleen gecontroleerd: boekingssleutel (zie KC14) + voldoen aan de 50% grens voor aanvullende opdrachten.; beide akkoord. NB zoals Shenita ook al heeft aangegeven is het lastig om deze check uit te voeren omdat er geen standaardproces is dat voorschrijft hoe F_ advies gegeven moeten worden. F_adviseurs geven bij de BC aan dat er voor hun werkzaamheden geen werkinstructie bestaat. Dit dient bij de BC 2019 aandacht te krijgen.\nKC10_2: n.v.t. Art 11 (ACD03/01) is van toepassing en hierbij hoeft er geen J advies te worden gevragd, dit is ook niet gebeurd.\nKC11_2: n.v.t. Gezien bedrag zou art 11 in oude cons lijst van toepassing zijn. K&C zou advies moeten geven. Ik weet niet waar K&C adviseur op toest, maar ik heb bij KC9 al vastgesteld dat aan de 50% grens wordt voldaan. Verder betreft dit een aanvullende opdracht die eerder EU is aanbesteed. Dus de juiste procedure is gevolgd + juist mandaat. Akkoord.",
    Controleur: "Remco"
  },
  {
    _id: 18,
    PostNr: 18,
    OrganisatieEenheid: "DRM",
    Afdeling: "Projecten en Programma's",
    Bureau: "Project Rijnland Route",
    Kostenplaats: 432,
    DocumentNummer: 300647,
    LeverancierInkoopOmschrijving:
      "Publiquest\n\nBezetting informatiecentrum Rijnlandroute\n\nPZH_2018_655231445",
    BedragFactuur: " � 18.261,83 ",
    BedragBesluit: " � 539.508 ",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "ja",
    KC2: "ja",
    KC3: "ja",
    KC4: "ja",
    KC5: "n.v.t.",
    KC6: "ja",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "n.v.t.",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "ja",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "Kc02c/d: Prestatie is beoordeeld door de BA M. Vellekoop. Gaat over inzet bezetting informatiecentrum Rijnlandroute. Deze heeft vooraf een urenbriefje getekend en achteraf ook de factuur geaccordeerd. Tevens heeft zij een toelichting per mail gegeven op welke wijze zij de prestatie heeft gecontroleerd. Tevens nog aanvullend bewijs mbt het informatiecentrum toegevoegd. Akkoord.\nKc05: nvt betreft uitvraag binnen ROVK\nKc07_1_Kc12_1: nvt betreft uitvraag binnen ROVK, geen machtiging/inkoopbesluit nodig.\nKc09_2_Kc12_2: Adviseurs niet noodzakelijk cf  'oude' consultatielijst (zie ACD 03.01) omdat dit uitvraag binnen ROVK betreft. Wel een adviseur BIR geraadpleegd. Adviseur akkoord met inhoud.",
    Controleur: "Ton"
  },
  {
    _id: 19,
    PostNr: 19,
    OrganisatieEenheid: "DLB",
    Afdeling: "Samenleving en Economie",
    Bureau: "Econom.Zaken",
    Kostenplaats: 396,
    DocumentNummer: 304584,
    LeverancierInkoopOmschrijving:
      "Tempo Team\n\nInzet MC Rollinger wk 49_52\n\nPZH_2018_669388522",
    BedragFactuur: " � 3.339,53 ",
    BedragBesluit: " � 10.523 ",
    SoortInkoop: "Dienst",
    SoortFactuur: "Match",
    KC1: "open",
    KC2: "open",
    KC3: "ja",
    KC4: "ja",
    KC5: "n.v.t.",
    KC6: "ja",
    KC7_1: "n.v.t.",
    KC7_2: "ja",
    KC8_1: "n.v.t.",
    KC8_2: "ja",
    KC9_1: "n.v.t.",
    KC9_2: "n.v.t.",
    KC10_1: "n.v.t.",
    KC10_2: "n.v.t.",
    KC11_1: "n.v.t.",
    KC11_2: "n.v.t.",
    KC12_1: "n.v.t.",
    KC12_2: "n.v.t.",
    KC13: "ja",
    KC14: "ja",
    KC15: "ja",
    KC16: "n.v.t.",
    Opmerkingen:
      "Kc01a Uurtarief factuur (29,23) niet cf VVB (totaal bedrag) en opdrachtbrief (uurtarief 29,16) en de offerte van 2_11_2018 (uurtarief 29,16). Tarief factuur 29,23 is wel conform een eerder verstuurd e_mail (31_10_2018). Betreft een geringe afwijking. Openstaand: Per mail 23_01_2018 gevraagd om verklaring aan de BA: Mariska Hakkenberg. Deze is pas 28_01_2018 aanwezig. \nKc02c/d: Prestatie is beoordeeld door de BA M. Hakkenberg. Gaat over inzet bezetting secretariaat. De factuur is door de BA akkoord bevonden middels het zetten van een paraaf. Openstaand: Per mail 23_01_2018 vraag gesteld hoe zij heeft vastgesteld dat de betrokken medewerkster ook het aantal gefactureerde uren aanwezig is geweest en dat  de werkzaamheden ook daadwerkelijk zijn uitgevoerd? BA is pas 28_01_2018 aanwezig.\nKc05: nvt betreft uitvraag binnen ROVK\nKC06b: Betreft verlenging op basis van eerdere opdracht. ROVK is van toepassing en nog geldig. Verlenging is mogelijk cf art 4.6. Wel in principe 1 maand voor einde oorspronkelijk opdracht. Dit is niet gehaald. Echter er zijn geen consequenties indien onder dezelfde voorwaarden wordt verlengd\nKc07_1_Kc12_1: nvt betreft uitvraag binnen ROVK, geen machtiging/inkoopbesluit nodig.\nKc09_2_Kc12_2: Adviseurs niet geraadpleegd en niet noodzakelijk cf  'oude' consultatielijst (zie ACD 03.01) omdat dit uitvraag binnen ROVK betreft. ",
    Controleur: "Ton"
  }
];

export function getWorkPrograms() {
  return workPrograms;
}

export function getWorkProgram(id) {
  return workPrograms.find(m => m._id === Number(id));
}

export function saveWorkProgram(workProgram) {
  let workProgramInDb = workPrograms.find(m => m._id === workProgram._id) || {};
  workProgramInDb.name = workProgram.name;
  workProgramInDb.genre = genresAPI.genres.find(
    g => g._id === workProgram.genreId
  );
  workProgramInDb.numberInStock = workProgram.numberInStock;
  workProgramInDb.dailyRentalRate = workProgram.dailyRentalRate;

  if (!workProgramInDb._id) {
    workProgramInDb._id = Date.now();
    workPrograms.push(workProgramInDb);
  }

  return workProgramInDb;
}

export function deleteWorkProgram(id) {
  let workProgramInDb = workPrograms.find(m => m._id === id);
  workPrograms.splice(workPrograms.indexOf(workProgramInDb), 1);
  return workProgramInDb;
}
